program: main.py
name: sweepdemo
method: grid

metric:
  goal: minimize
  name: val-loss
parameters:
  batch_size: 
    values: [8, 16, 32, 64, 128, 256, 1024]

command:
  - ../.venv/bin/python
  - ${program}
  - ${args}